# Generated by Django 6.0.6 on 2026-07-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
